import React from 'react';
import {
  FileText,
  FileSpreadsheet,
  FileCheck,
  Layers,
  Image as ImageIcon,
  RectangleHorizontal,
  RectangleVertical,
  Square,
  ReceiptText,
  CalendarClock,
  FileSignature,
  Boxes,
  ImageDown,
  Ratio,
  Terminal,
  Cpu,
  FileCode2,
  Binary,
  ScanEye,
  Orbit,
  Scroll,
  Compass,
  Feather,
  TreePine,
  Palette,
  Leaf,
  Coins,
  Hourglass,
  Flame,
  SlidersHorizontal,
  Aperture,
  Spline,
  Files,
  Timer,
  CheckSquare2,
  Grid,
  Focus,
  Grid3X3,
  Printer,
  AlarmClock,
  Pencil,
  Wrench,
  Monitor,
  Box,
  Rocket,
  Telescope,
  Sparkles,
  Sun,
  Maximize2,
  Sparkle,
  CalendarHeart,
  PenTool,
  Layers2,
  Camera,
  Shapes,
  Moon,
  Zap,
  Snowflake,
  Tv,
} from 'lucide-react';
import { Theme, ThemeType, IconStyleType } from '../types';

export interface ThemeMeta {
  id: ThemeType;
  label: string;
  enLabel: string;
  icon: React.ReactNode;
  colorDot: string;
  iconSetName: string;
  iconSetEn: string;
  description: string;
  enDescription: string;
  defaultWallpaper: string;
  accentColor: string;
  previewIcons: React.ReactNode[];
}

export const THEME_REGISTRY: Record<ThemeType, ThemeMeta> = {
  [Theme.DARK]: {
    id: Theme.DARK,
    label: 'Dark',
    enLabel: 'Dark',
    icon: <Moon className="w-3.5 h-3.5 text-indigo-400" />,
    colorDot: 'bg-indigo-500',
    iconSetName: 'macOS Classic Glass Squircles',
    iconSetEn: 'macOS Classic Glass Squircles',
    description: 'Deep indigo space & classic Apple glass icons',
    enDescription: 'Deep indigo space & classic Apple glass icons',
    defaultWallpaper: 'cyber-midnight',
    accentColor: 'indigo',
    previewIcons: [
      <FileText key="prev-dark-0" className="w-3.5 h-3.5 text-rose-400" />,
      <FileSpreadsheet key="prev-dark-1" className="w-3.5 h-3.5 text-emerald-400" />,
      <FileCheck key="prev-dark-2" className="w-3.5 h-3.5 text-purple-400" />,
      <Layers key="prev-dark-3" className="w-3.5 h-3.5 text-cyan-400" />,
    ],
  },
  [Theme.LIGHT]: {
    id: Theme.LIGHT,
    label: 'Light',
    enLabel: 'Light',
    icon: <Sun className="w-3.5 h-3.5 text-amber-500" />,
    colorDot: 'bg-amber-400',
    iconSetName: 'Aqua Vibrant Studio Icons',
    iconSetEn: 'Aqua Vibrant Studio Icons',
    description: 'Clean studio daylight & vibrant aqua badges',
    enDescription: 'Clean studio daylight & vibrant aqua badges',
    defaultWallpaper: 'blue',
    accentColor: 'blue',
    previewIcons: [
      <ReceiptText key="prev-light-0" className="w-3.5 h-3.5 text-rose-500" />,
      <CalendarClock key="prev-light-1" className="w-3.5 h-3.5 text-teal-500" />,
      <FileSignature key="prev-light-2" className="w-3.5 h-3.5 text-indigo-500" />,
      <Boxes key="prev-light-3" className="w-3.5 h-3.5 text-sky-500" />,
    ],
  },
  [Theme.CYBERPUNK]: {
    id: Theme.CYBERPUNK,
    label: 'Cyberpunk',
    enLabel: 'Cyberpunk',
    icon: <Zap className="w-3.5 h-3.5 text-pink-400" />,
    colorDot: 'bg-pink-500',
    iconSetName: 'Netrunner Terminal & HUD Glyphs',
    iconSetEn: 'Netrunner Terminal & HUD Glyphs',
    description: 'Pitch-black OLED, terminal code & neon circuits',
    enDescription: 'Pitch-black OLED, terminal code & neon circuits',
    defaultWallpaper: 'cyberpunk',
    accentColor: 'pink',
    previewIcons: [
      <Terminal key="prev-cyber-0" className="w-3.5 h-3.5 text-pink-400" />,
      <Cpu key="prev-cyber-1" className="w-3.5 h-3.5 text-emerald-400" />,
      <FileCode2 key="prev-cyber-2" className="w-3.5 h-3.5 text-cyan-400" />,
      <Binary key="prev-cyber-3" className="w-3.5 h-3.5 text-amber-400" />,
    ],
  },
  [Theme.FOREST]: {
    id: Theme.FOREST,
    label: 'Forest',
    enLabel: 'Forest',
    icon: <TreePine className="w-3.5 h-3.5 text-emerald-400" />,
    colorDot: 'bg-emerald-500',
    iconSetName: 'Botanical Scroll & Compass Glyphs',
    iconSetEn: 'Botanical Scroll & Compass Glyphs',
    description: 'Deep evergreen, ancient scrolls & brass compass',
    enDescription: 'Deep evergreen, ancient scrolls & brass compass',
    defaultWallpaper: 'forest',
    accentColor: 'emerald',
    previewIcons: [
      <Scroll key="prev-forest-0" className="w-3.5 h-3.5 text-amber-400" />,
      <Compass key="prev-forest-1" className="w-3.5 h-3.5 text-emerald-400" />,
      <Feather key="prev-forest-2" className="w-3.5 h-3.5 text-teal-400" />,
      <TreePine key="prev-forest-3" className="w-3.5 h-3.5 text-lime-400" />,
    ],
  },
  [Theme.SUNSET]: {
    id: Theme.SUNSET,
    label: 'Sunset',
    enLabel: 'Sunset',
    icon: <Flame className="w-3.5 h-3.5 text-orange-400" />,
    colorDot: 'bg-orange-500',
    iconSetName: 'Golden Coins, Hourglass & Ember Glyphs',
    iconSetEn: 'Golden Coins, Hourglass & Ember Glyphs',
    description: 'Warm sunset glow, gold treasury & dusk hour',
    enDescription: 'Warm sunset glow, gold treasury & dusk hour',
    defaultWallpaper: 'sunset',
    accentColor: 'orange',
    previewIcons: [
      <Coins key="prev-sunset-0" className="w-3.5 h-3.5 text-amber-400" />,
      <Hourglass key="prev-sunset-1" className="w-3.5 h-3.5 text-orange-400" />,
      <Flame key="prev-sunset-2" className="w-3.5 h-3.5 text-rose-400" />,
      <Aperture key="prev-sunset-3" className="w-3.5 h-3.5 text-yellow-400" />,
    ],
  },
  [Theme.NORDIC]: {
    id: Theme.NORDIC,
    label: 'Nordic',
    enLabel: 'Nordic',
    icon: <Snowflake className="w-3.5 h-3.5 text-sky-400" />,
    colorDot: 'bg-sky-400',
    iconSetName: 'Nordic Frost Minimalist Glyphs',
    iconSetEn: 'Nordic Frost Minimalist Glyphs',
    description: 'Crisp polar ice blue & Scandinavian precision grid',
    enDescription: 'Crisp polar ice blue & Scandinavian precision grid',
    defaultWallpaper: 'nordic',
    accentColor: 'sky',
    previewIcons: [
      <Files key="prev-nordic-0" className="w-3.5 h-3.5 text-sky-300" />,
      <Timer key="prev-nordic-1" className="w-3.5 h-3.5 text-cyan-300" />,
      <CheckSquare2 key="prev-nordic-2" className="w-3.5 h-3.5 text-indigo-300" />,
      <Grid key="prev-nordic-3" className="w-3.5 h-3.5 text-blue-300" />,
    ],
  },
  [Theme.RETRO]: {
    id: Theme.RETRO,
    label: 'Retro',
    enLabel: 'Retro',
    icon: <Tv className="w-3.5 h-3.5 text-stone-400" />,
    colorDot: 'bg-stone-400',
    iconSetName: 'Classic 1984 Dot-Matrix & Pixel Icons',
    iconSetEn: 'Classic 1984 Dot-Matrix & Pixel Icons',
    description: 'Vintage 1984 Mac OS, dot-matrix printer & CRT monitor',
    enDescription: 'Vintage 1984 Mac OS, dot-matrix printer & CRT monitor',
    defaultWallpaper: 'retro',
    accentColor: 'stone',
    previewIcons: [
      <Printer key="prev-retro-0" className="w-3.5 h-3.5 text-stone-300" />,
      <AlarmClock key="prev-retro-1" className="w-3.5 h-3.5 text-amber-300" />,
      <Pencil key="prev-retro-2" className="w-3.5 h-3.5 text-sky-300" />,
      <Wrench key="prev-retro-3" className="w-3.5 h-3.5 text-emerald-300" />,
    ],
  },
  [Theme.NEBULA]: {
    id: Theme.NEBULA,
    label: 'Nebula',
    enLabel: 'Nebula',
    icon: <Rocket className="w-3.5 h-3.5 text-violet-400" />,
    colorDot: 'bg-violet-500',
    iconSetName: 'Deep-Space Starship & Orbit Telemetry',
    iconSetEn: 'Deep-Space Starship & Orbit Telemetry',
    description: 'Deep space ultraviolet, orbital telemetry & rocket ship',
    enDescription: 'Deep space ultraviolet, orbital telemetry & rocket ship',
    defaultWallpaper: 'nebula',
    accentColor: 'violet',
    previewIcons: [
      <Rocket key="prev-nebula-0" className="w-3.5 h-3.5 text-violet-400" />,
      <Orbit key="prev-nebula-1" className="w-3.5 h-3.5 text-cyan-400" />,
      <Telescope key="prev-nebula-2" className="w-3.5 h-3.5 text-fuchsia-400" />,
      <Sparkles key="prev-nebula-3" className="w-3.5 h-3.5 text-pink-300" />,
    ],
  },
  [Theme.ROSE]: {
    id: Theme.ROSE,
    label: 'Rose',
    enLabel: 'Rose',
    icon: <Sparkle className="w-3.5 h-3.5 text-rose-400" />,
    colorDot: 'bg-rose-400',
    iconSetName: 'Rose Quartz & Champagne Atelier Icons',
    iconSetEn: 'Rose Quartz & Champagne Atelier Icons',
    description: 'Blush sakura pink, champagne gold & rose quartz styling',
    enDescription: 'Blush sakura pink, champagne gold & rose quartz styling',
    defaultWallpaper: 'rose',
    accentColor: 'rose',
    previewIcons: [
      <Sparkle key="prev-rose-0" className="w-3.5 h-3.5 text-rose-300" />,
      <CalendarHeart key="prev-rose-1" className="w-3.5 h-3.5 text-pink-300" />,
      <PenTool key="prev-rose-2" className="w-3.5 h-3.5 text-amber-300" />,
      <Layers2 key="prev-rose-3" className="w-3.5 h-3.5 text-purple-300" />,
    ],
  },
};

export interface DockItemThemedConfig {
  id: string;
  icon: React.ReactNode;
  gradient: string;
  shadow: string;
  borderStyle: string;
  badgeStyle?: string;
  glowAura: string;
  themeBadgeText?: string;
}

export function getThemeIconsConfig(
  theme: ThemeType,
  shapeType: 'horizontal' | 'vertical' | 'square' | 'invalid' = 'horizontal'
): Record<string, DockItemThemedConfig> {
  switch (theme) {
    case Theme.CYBERPUNK:
      return {
        quotes: {
          id: 'quotes',
          icon: <Terminal className="w-4 h-4 sm:w-5 sm:h-5 text-pink-300" />,
          gradient: 'from-pink-600 via-purple-700 to-black',
          shadow: 'shadow-[0_0_16px_rgba(236,72,153,0.5)]',
          borderStyle: 'border border-pink-400/80 shadow-[inset_0_0_8px_rgba(236,72,153,0.4)]',
          glowAura: 'from-pink-500 via-magenta-500 to-cyan-500',
          themeBadgeText: 'LOG',
        },
        schedule: {
          id: 'schedule',
          icon: <Cpu className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-300" />,
          gradient: 'from-emerald-600 via-teal-800 to-black',
          shadow: 'shadow-[0_0_16px_rgba(16,185,129,0.5)]',
          borderStyle: 'border border-emerald-400/80 shadow-[inset_0_0_8px_rgba(16,185,129,0.4)]',
          glowAura: 'from-emerald-400 to-cyan-500',
          themeBadgeText: 'CPU',
        },
        'pdf-editor': {
          id: 'pdf-editor',
          icon: <FileCode2 className="w-4 h-4 sm:w-5 sm:h-5 text-cyan-300" />,
          gradient: 'from-cyan-600 via-blue-800 to-black',
          shadow: 'shadow-[0_0_16px_rgba(6,182,212,0.5)]',
          borderStyle: 'border border-cyan-400/80 shadow-[inset_0_0_8px_rgba(6,182,212,0.4)]',
          glowAura: 'from-cyan-400 to-blue-500',
          themeBadgeText: 'HEX',
        },
        'pdf-tools': {
          id: 'pdf-tools',
          icon: <Binary className="w-4 h-4 sm:w-5 sm:h-5 text-amber-300" />,
          gradient: 'from-amber-600 via-orange-800 to-black',
          shadow: 'shadow-[0_0_16px_rgba(245,158,11,0.5)]',
          borderStyle: 'border border-amber-400/80 shadow-[inset_0_0_8px_rgba(245,158,11,0.4)]',
          glowAura: 'from-amber-400 to-pink-500',
          themeBadgeText: 'OPS',
        },
        converter: {
          id: 'converter',
          icon: <ScanEye className="w-4 h-4 sm:w-5 sm:h-5 text-fuchsia-300" />,
          gradient: 'from-fuchsia-600 via-pink-800 to-black',
          shadow: 'shadow-[0_0_16px_rgba(217,70,239,0.5)]',
          borderStyle: 'border border-fuchsia-400/80 shadow-[inset_0_0_8px_rgba(217,70,239,0.4)]',
          glowAura: 'from-fuchsia-400 to-cyan-500',
          themeBadgeText: 'SCAN',
        },
        shape: {
          id: 'shape',
          icon: <Orbit className="w-4 h-4 sm:w-5 sm:h-5 text-cyan-200" />,
          gradient: 'from-blue-600 via-indigo-900 to-black',
          shadow: 'shadow-[0_0_16px_rgba(59,130,246,0.5)]',
          borderStyle: 'border border-cyan-400/80 shadow-[inset_0_0_8px_rgba(59,130,246,0.4)]',
          glowAura: 'from-cyan-400 to-indigo-500',
          themeBadgeText: 'DIM',
        },
      };

    case Theme.FOREST:
      return {
        quotes: {
          id: 'quotes',
          icon: <Scroll className="w-4 h-4 sm:w-5 sm:h-5 text-amber-200" />,
          gradient: 'from-amber-700 via-emerald-800 to-emerald-950',
          shadow: 'shadow-emerald-900/50',
          borderStyle: 'border border-emerald-400/40 shadow-[inset_0_1px_1px_rgba(255,255,255,0.3)]',
          glowAura: 'from-emerald-500 via-teal-400 to-amber-500',
          themeBadgeText: 'SCROLL',
        },
        schedule: {
          id: 'schedule',
          icon: <Compass className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-200" />,
          gradient: 'from-emerald-600 via-teal-700 to-green-900',
          shadow: 'shadow-emerald-900/50',
          borderStyle: 'border border-emerald-300/40 shadow-[inset_0_1px_1px_rgba(255,255,255,0.3)]',
          glowAura: 'from-emerald-400 to-lime-500',
          themeBadgeText: 'DIAL',
        },
        'pdf-editor': {
          id: 'pdf-editor',
          icon: <Feather className="w-4 h-4 sm:w-5 sm:h-5 text-teal-200" />,
          gradient: 'from-teal-600 via-emerald-700 to-emerald-950',
          shadow: 'shadow-teal-900/50',
          borderStyle: 'border border-teal-300/40 shadow-[inset_0_1px_1px_rgba(255,255,255,0.3)]',
          glowAura: 'from-teal-400 to-emerald-600',
          themeBadgeText: 'QUILL',
        },
        'pdf-tools': {
          id: 'pdf-tools',
          icon: <TreePine className="w-4 h-4 sm:w-5 sm:h-5 text-lime-200" />,
          gradient: 'from-green-600 via-emerald-800 to-teal-950',
          shadow: 'shadow-green-900/50',
          borderStyle: 'border border-lime-300/40 shadow-[inset_0_1px_1px_rgba(255,255,255,0.3)]',
          glowAura: 'from-lime-400 to-emerald-500',
          themeBadgeText: 'PINE',
        },
        converter: {
          id: 'converter',
          icon: <Palette className="w-4 h-4 sm:w-5 sm:h-5 text-yellow-200" />,
          gradient: 'from-amber-600 via-emerald-700 to-green-950',
          shadow: 'shadow-amber-900/50',
          borderStyle: 'border border-amber-300/40 shadow-[inset_0_1px_1px_rgba(255,255,255,0.3)]',
          glowAura: 'from-amber-400 to-emerald-500',
          themeBadgeText: 'FLORA',
        },
        shape: {
          id: 'shape',
          icon: <Leaf className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-200" />,
          gradient: 'from-emerald-500 via-teal-800 to-green-950',
          shadow: 'shadow-emerald-900/50',
          borderStyle: 'border border-emerald-300/40 shadow-[inset_0_1px_1px_rgba(255,255,255,0.3)]',
          glowAura: 'from-emerald-400 to-teal-500',
          themeBadgeText: 'LEAF',
        },
      };

    case Theme.SUNSET:
      return {
        quotes: {
          id: 'quotes',
          icon: <Coins className="w-4 h-4 sm:w-5 sm:h-5 text-amber-200" />,
          gradient: 'from-amber-500 via-orange-600 to-rose-700',
          shadow: 'shadow-orange-600/40',
          borderStyle: 'border border-amber-300/50 shadow-[inset_0_1px_2px_rgba(255,255,255,0.35)]',
          glowAura: 'from-amber-400 via-orange-500 to-rose-500',
          themeBadgeText: 'GOLD',
        },
        schedule: {
          id: 'schedule',
          icon: <Hourglass className="w-4 h-4 sm:w-5 sm:h-5 text-orange-200" />,
          gradient: 'from-orange-500 via-rose-600 to-purple-800',
          shadow: 'shadow-orange-600/40',
          borderStyle: 'border border-orange-300/50 shadow-[inset_0_1px_2px_rgba(255,255,255,0.35)]',
          glowAura: 'from-orange-400 to-rose-500',
          themeBadgeText: 'HOUR',
        },
        'pdf-editor': {
          id: 'pdf-editor',
          icon: <Flame className="w-4 h-4 sm:w-5 sm:h-5 text-rose-200" />,
          gradient: 'from-rose-600 via-pink-700 to-orange-800',
          shadow: 'shadow-rose-600/40',
          borderStyle: 'border border-rose-300/50 shadow-[inset_0_1px_2px_rgba(255,255,255,0.35)]',
          glowAura: 'from-rose-400 to-orange-500',
          themeBadgeText: 'EMBER',
        },
        'pdf-tools': {
          id: 'pdf-tools',
          icon: <SlidersHorizontal className="w-4 h-4 sm:w-5 sm:h-5 text-yellow-200" />,
          gradient: 'from-amber-600 via-red-600 to-purple-900',
          shadow: 'shadow-red-600/40',
          borderStyle: 'border border-amber-300/50 shadow-[inset_0_1px_2px_rgba(255,255,255,0.35)]',
          glowAura: 'from-amber-400 to-red-500',
          themeBadgeText: 'DUSK',
        },
        converter: {
          id: 'converter',
          icon: <Aperture className="w-4 h-4 sm:w-5 sm:h-5 text-orange-200" />,
          gradient: 'from-orange-600 via-amber-600 to-rose-900',
          shadow: 'shadow-orange-600/40',
          borderStyle: 'border border-orange-300/50 shadow-[inset_0_1px_2px_rgba(255,255,255,0.35)]',
          glowAura: 'from-orange-400 to-amber-500',
          themeBadgeText: 'LENS',
        },
        shape: {
          id: 'shape',
          icon: <Spline className="w-4 h-4 sm:w-5 sm:h-5 text-yellow-200" />,
          gradient: 'from-red-600 via-orange-600 to-amber-700',
          shadow: 'shadow-red-600/40',
          borderStyle: 'border border-yellow-300/50 shadow-[inset_0_1px_2px_rgba(255,255,255,0.35)]',
          glowAura: 'from-yellow-400 to-orange-500',
          themeBadgeText: 'CURV',
        },
      };

    case Theme.NORDIC:
      return {
        quotes: {
          id: 'quotes',
          icon: <Files className="w-4 h-4 sm:w-5 sm:h-5 text-sky-200" />,
          gradient: 'from-sky-700 via-slate-800 to-slate-950',
          shadow: 'shadow-sky-800/40',
          borderStyle: 'border border-sky-300/40 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-sky-400 via-cyan-400 to-blue-500',
          themeBadgeText: 'FROST',
        },
        schedule: {
          id: 'schedule',
          icon: <Timer className="w-4 h-4 sm:w-5 sm:h-5 text-cyan-200" />,
          gradient: 'from-cyan-700 via-slate-800 to-slate-950',
          shadow: 'shadow-cyan-800/40',
          borderStyle: 'border border-cyan-300/40 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-cyan-400 to-sky-500',
          themeBadgeText: 'CHRONO',
        },
        'pdf-editor': {
          id: 'pdf-editor',
          icon: <CheckSquare2 className="w-4 h-4 sm:w-5 sm:h-5 text-indigo-200" />,
          gradient: 'from-blue-700 via-slate-800 to-slate-950',
          shadow: 'shadow-blue-800/40',
          borderStyle: 'border border-blue-300/40 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-blue-400 to-indigo-500',
          themeBadgeText: 'PROOF',
        },
        'pdf-tools': {
          id: 'pdf-tools',
          icon: <Grid className="w-4 h-4 sm:w-5 sm:h-5 text-slate-200" />,
          gradient: 'from-slate-600 via-slate-800 to-slate-950',
          shadow: 'shadow-slate-800/40',
          borderStyle: 'border border-slate-300/40 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-slate-300 to-sky-400',
          themeBadgeText: 'GRID',
        },
        converter: {
          id: 'converter',
          icon: <Focus className="w-4 h-4 sm:w-5 sm:h-5 text-sky-200" />,
          gradient: 'from-teal-700 via-slate-800 to-slate-950',
          shadow: 'shadow-teal-800/40',
          borderStyle: 'border border-teal-300/40 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-teal-400 to-sky-400',
          themeBadgeText: 'OPTIC',
        },
        shape: {
          id: 'shape',
          icon: <Grid3X3 className="w-4 h-4 sm:w-5 sm:h-5 text-blue-200" />,
          gradient: 'from-indigo-700 via-slate-800 to-slate-950',
          shadow: 'shadow-indigo-800/40',
          borderStyle: 'border border-indigo-300/40 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-indigo-400 to-blue-400',
          themeBadgeText: 'POLAR',
        },
      };

    case Theme.RETRO:
      return {
        quotes: {
          id: 'quotes',
          icon: <Printer className="w-4 h-4 sm:w-5 sm:h-5 text-stone-100" />,
          gradient: 'from-stone-600 via-stone-700 to-stone-900',
          shadow: 'shadow-stone-900/60',
          borderStyle: 'border-2 border-stone-300/60 shadow-[inset_1px_1px_0_rgba(255,255,255,0.8),inset_-1px_-1px_0_rgba(0,0,0,0.8)]',
          glowAura: 'from-stone-400 via-amber-300 to-sky-400',
          themeBadgeText: 'PRINT',
        },
        schedule: {
          id: 'schedule',
          icon: <AlarmClock className="w-4 h-4 sm:w-5 sm:h-5 text-amber-200" />,
          gradient: 'from-amber-700 via-stone-800 to-stone-950',
          shadow: 'shadow-stone-900/60',
          borderStyle: 'border-2 border-amber-300/60 shadow-[inset_1px_1px_0_rgba(255,255,255,0.8),inset_-1px_-1px_0_rgba(0,0,0,0.8)]',
          glowAura: 'from-amber-400 to-stone-400',
          themeBadgeText: 'BELL',
        },
        'pdf-editor': {
          id: 'pdf-editor',
          icon: <Pencil className="w-4 h-4 sm:w-5 sm:h-5 text-sky-200" />,
          gradient: 'from-sky-700 via-stone-800 to-stone-950',
          shadow: 'shadow-stone-900/60',
          borderStyle: 'border-2 border-sky-300/60 shadow-[inset_1px_1px_0_rgba(255,255,255,0.8),inset_-1px_-1px_0_rgba(0,0,0,0.8)]',
          glowAura: 'from-sky-400 to-stone-400',
          themeBadgeText: 'WRITE',
        },
        'pdf-tools': {
          id: 'pdf-tools',
          icon: <Wrench className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-200" />,
          gradient: 'from-emerald-700 via-stone-800 to-stone-950',
          shadow: 'shadow-stone-900/60',
          borderStyle: 'border-2 border-emerald-300/60 shadow-[inset_1px_1px_0_rgba(255,255,255,0.8),inset_-1px_-1px_0_rgba(0,0,0,0.8)]',
          glowAura: 'from-emerald-400 to-stone-400',
          themeBadgeText: 'TOOL',
        },
        converter: {
          id: 'converter',
          icon: <Monitor className="w-4 h-4 sm:w-5 sm:h-5 text-purple-200" />,
          gradient: 'from-purple-700 via-stone-800 to-stone-950',
          shadow: 'shadow-stone-900/60',
          borderStyle: 'border-2 border-purple-300/60 shadow-[inset_1px_1px_0_rgba(255,255,255,0.8),inset_-1px_-1px_0_rgba(0,0,0,0.8)]',
          glowAura: 'from-purple-400 to-stone-400',
          themeBadgeText: 'CRT',
        },
        shape: {
          id: 'shape',
          icon: <Box className="w-4 h-4 sm:w-5 sm:h-5 text-stone-200" />,
          gradient: 'from-stone-700 via-stone-800 to-stone-950',
          shadow: 'shadow-stone-900/60',
          borderStyle: 'border-2 border-stone-300/60 shadow-[inset_1px_1px_0_rgba(255,255,255,0.8),inset_-1px_-1px_0_rgba(0,0,0,0.8)]',
          glowAura: 'from-stone-400 to-stone-600',
          themeBadgeText: 'DRAW',
        },
      };

    case Theme.NEBULA:
      return {
        quotes: {
          id: 'quotes',
          icon: <Rocket className="w-4 h-4 sm:w-5 sm:h-5 text-fuchsia-300" />,
          gradient: 'from-fuchsia-600 via-indigo-900 to-black',
          shadow: 'shadow-[0_0_18px_rgba(217,70,239,0.5)]',
          borderStyle: 'border border-fuchsia-400/70 shadow-[inset_0_0_10px_rgba(217,70,239,0.3)]',
          glowAura: 'from-fuchsia-500 via-violet-500 to-cyan-500',
          themeBadgeText: 'WARP',
        },
        schedule: {
          id: 'schedule',
          icon: <Orbit className="w-4 h-4 sm:w-5 sm:h-5 text-cyan-300" />,
          gradient: 'from-indigo-600 via-blue-900 to-black',
          shadow: 'shadow-[0_0_18px_rgba(6,182,212,0.5)]',
          borderStyle: 'border border-cyan-400/70 shadow-[inset_0_0_10px_rgba(6,182,212,0.3)]',
          glowAura: 'from-cyan-400 to-indigo-500',
          themeBadgeText: 'ASTR',
        },
        'pdf-editor': {
          id: 'pdf-editor',
          icon: <Telescope className="w-4 h-4 sm:w-5 sm:h-5 text-violet-300" />,
          gradient: 'from-violet-600 via-purple-900 to-black',
          shadow: 'shadow-[0_0_18px_rgba(139,92,246,0.5)]',
          borderStyle: 'border border-violet-400/70 shadow-[inset_0_0_10px_rgba(139,92,246,0.3)]',
          glowAura: 'from-violet-400 to-fuchsia-500',
          themeBadgeText: 'DEEP',
        },
        'pdf-tools': {
          id: 'pdf-tools',
          icon: <Sparkles className="w-4 h-4 sm:w-5 sm:h-5 text-pink-300" />,
          gradient: 'from-pink-600 via-violet-900 to-black',
          shadow: 'shadow-[0_0_18px_rgba(236,72,153,0.5)]',
          borderStyle: 'border border-pink-400/70 shadow-[inset_0_0_10px_rgba(236,72,153,0.3)]',
          glowAura: 'from-pink-400 to-violet-500',
          themeBadgeText: 'NOVA',
        },
        converter: {
          id: 'converter',
          icon: <Sun className="w-4 h-4 sm:w-5 sm:h-5 text-amber-300" />,
          gradient: 'from-amber-600 via-purple-900 to-black',
          shadow: 'shadow-[0_0_18px_rgba(245,158,11,0.5)]',
          borderStyle: 'border border-amber-400/70 shadow-[inset_0_0_10px_rgba(245,158,11,0.3)]',
          glowAura: 'from-amber-400 to-violet-500',
          themeBadgeText: 'SOL',
        },
        shape: {
          id: 'shape',
          icon: <Maximize2 className="w-4 h-4 sm:w-5 sm:h-5 text-blue-300" />,
          gradient: 'from-blue-600 via-indigo-950 to-black',
          shadow: 'shadow-[0_0_18px_rgba(59,130,246,0.5)]',
          borderStyle: 'border border-blue-400/70 shadow-[inset_0_0_10px_rgba(59,130,246,0.3)]',
          glowAura: 'from-blue-400 to-cyan-500',
          themeBadgeText: 'SPEC',
        },
      };

    case Theme.ROSE:
      return {
        quotes: {
          id: 'quotes',
          icon: <Sparkle className="w-4 h-4 sm:w-5 sm:h-5 text-rose-200" />,
          gradient: 'from-rose-500 via-pink-600 to-rose-900',
          shadow: 'shadow-rose-500/40',
          borderStyle: 'border border-rose-300/60 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-rose-400 via-pink-300 to-amber-300',
          themeBadgeText: 'GOLD',
        },
        schedule: {
          id: 'schedule',
          icon: <CalendarHeart className="w-4 h-4 sm:w-5 sm:h-5 text-pink-200" />,
          gradient: 'from-pink-500 via-rose-600 to-purple-900',
          shadow: 'shadow-pink-500/40',
          borderStyle: 'border border-pink-300/60 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-pink-400 to-rose-400',
          themeBadgeText: 'PLAN',
        },
        'pdf-editor': {
          id: 'pdf-editor',
          icon: <PenTool className="w-4 h-4 sm:w-5 sm:h-5 text-amber-200" />,
          gradient: 'from-rose-600 via-amber-700 to-stone-900',
          shadow: 'shadow-rose-500/40',
          borderStyle: 'border border-amber-300/60 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-amber-300 to-rose-400',
          themeBadgeText: 'ATEL',
        },
        'pdf-tools': {
          id: 'pdf-tools',
          icon: <Layers2 className="w-4 h-4 sm:w-5 sm:h-5 text-purple-200" />,
          gradient: 'from-pink-600 via-purple-700 to-rose-950',
          shadow: 'shadow-purple-500/40',
          borderStyle: 'border border-purple-300/60 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-purple-400 to-rose-400',
          themeBadgeText: 'SUITE',
        },
        converter: {
          id: 'converter',
          icon: <Camera className="w-4 h-4 sm:w-5 sm:h-5 text-rose-200" />,
          gradient: 'from-rose-500 via-pink-700 to-stone-900',
          shadow: 'shadow-rose-500/40',
          borderStyle: 'border border-rose-300/60 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-rose-400 to-pink-400',
          themeBadgeText: 'PHOTO',
        },
        shape: {
          id: 'shape',
          icon: <Shapes className="w-4 h-4 sm:w-5 sm:h-5 text-pink-200" />,
          gradient: 'from-pink-600 via-rose-700 to-purple-950',
          shadow: 'shadow-pink-500/40',
          borderStyle: 'border border-pink-300/60 shadow-[inset_0_1px_2px_rgba(255,255,255,0.4)]',
          glowAura: 'from-pink-400 to-amber-300',
          themeBadgeText: 'PETAL',
        },
      };

    case Theme.LIGHT:
      return {
        quotes: {
          id: 'quotes',
          icon: <ReceiptText className="w-4 h-4 sm:w-5 sm:h-5 text-white" />,
          gradient: 'from-rose-500 via-red-500 to-amber-500',
          shadow: 'shadow-rose-500/25',
          borderStyle: 'border border-white/60 shadow-md',
          glowAura: 'from-rose-400 via-amber-300 to-blue-400',
          themeBadgeText: 'BILL',
        },
        schedule: {
          id: 'schedule',
          icon: <CalendarClock className="w-4 h-4 sm:w-5 sm:h-5 text-white" />,
          gradient: 'from-emerald-500 via-teal-500 to-cyan-500',
          shadow: 'shadow-emerald-500/25',
          borderStyle: 'border border-white/60 shadow-md',
          glowAura: 'from-emerald-400 to-cyan-400',
          themeBadgeText: 'TIME',
        },
        'pdf-editor': {
          id: 'pdf-editor',
          icon: <FileSignature className="w-4 h-4 sm:w-5 sm:h-5 text-white" />,
          gradient: 'from-purple-500 via-indigo-500 to-blue-500',
          shadow: 'shadow-purple-500/25',
          borderStyle: 'border border-white/60 shadow-md',
          glowAura: 'from-purple-400 to-blue-400',
          themeBadgeText: 'SIGN',
        },
        'pdf-tools': {
          id: 'pdf-tools',
          icon: <Boxes className="w-4 h-4 sm:w-5 sm:h-5 text-white" />,
          gradient: 'from-cyan-500 via-blue-500 to-indigo-500',
          shadow: 'shadow-blue-500/25',
          borderStyle: 'border border-white/60 shadow-md',
          glowAura: 'from-cyan-400 to-blue-500',
          themeBadgeText: 'BOX',
        },
        converter: {
          id: 'converter',
          icon: <ImageDown className="w-4 h-4 sm:w-5 sm:h-5 text-white" />,
          gradient: 'from-teal-500 via-cyan-500 to-sky-500',
          shadow: 'shadow-cyan-500/25',
          borderStyle: 'border border-white/60 shadow-md',
          glowAura: 'from-teal-400 to-sky-400',
          themeBadgeText: 'IMG',
        },
        shape: {
          id: 'shape',
          icon: <Ratio className="w-4 h-4 sm:w-5 sm:h-5 text-white" />,
          gradient: 'from-blue-500 via-indigo-500 to-cyan-500',
          shadow: 'shadow-blue-500/25',
          borderStyle: 'border border-white/60 shadow-md',
          glowAura: 'from-blue-400 to-indigo-400',
          themeBadgeText: 'ASPECT',
        },
      };

    case Theme.DARK:
    default:
      return {
        quotes: {
          id: 'quotes',
          icon: <FileText className="w-4 h-4 sm:w-5 sm:h-5" />,
          gradient: 'from-rose-600 via-pink-500 to-amber-500',
          shadow: 'shadow-rose-500/30',
          borderStyle: 'border border-white/35 shadow-md',
          glowAura: 'from-rose-500 via-pink-500 to-amber-500',
          themeBadgeText: 'DOC',
        },
        schedule: {
          id: 'schedule',
          icon: <FileSpreadsheet className="w-4 h-4 sm:w-5 sm:h-5" />,
          gradient: 'from-emerald-600 via-teal-500 to-cyan-500',
          shadow: 'shadow-emerald-500/30',
          borderStyle: 'border border-white/35 shadow-md',
          glowAura: 'from-emerald-500 to-cyan-500',
          themeBadgeText: 'XLS',
        },
        'pdf-editor': {
          id: 'pdf-editor',
          icon: <FileCheck className="w-4 h-4 sm:w-5 sm:h-5" />,
          gradient: 'from-purple-600 via-indigo-600 to-blue-500',
          shadow: 'shadow-purple-500/30',
          borderStyle: 'border border-white/35 shadow-md',
          glowAura: 'from-purple-500 to-blue-500',
          themeBadgeText: 'PDF',
        },
        'pdf-tools': {
          id: 'pdf-tools',
          icon: <Layers className="w-4 h-4 sm:w-5 sm:h-5" />,
          gradient: 'from-cyan-600 via-blue-600 to-indigo-600',
          shadow: 'shadow-blue-500/30',
          borderStyle: 'border border-white/35 shadow-md',
          glowAura: 'from-cyan-500 to-indigo-500',
          themeBadgeText: 'TOOL',
        },
        converter: {
          id: 'converter',
          icon: <ImageIcon className="w-4 h-4 sm:w-5 sm:h-5" />,
          gradient: 'from-teal-600 via-cyan-600 to-sky-500',
          shadow: 'shadow-cyan-500/30',
          borderStyle: 'border border-white/35 shadow-md',
          glowAura: 'from-teal-500 to-sky-500',
          themeBadgeText: 'CONV',
        },
        shape: {
          id: 'shape',
          icon:
            shapeType === 'horizontal' ? (
              <RectangleHorizontal className="w-4 h-4 sm:w-5 sm:h-5" />
            ) : shapeType === 'vertical' ? (
              <RectangleVertical className="w-4 h-4 sm:w-5 sm:h-5" />
            ) : (
              <Square className="w-4 h-4 sm:w-5 sm:h-5" />
            ),
          gradient: 'from-blue-600 via-indigo-600 to-cyan-500',
          shadow: 'shadow-blue-500/30',
          borderStyle: 'border border-white/35 shadow-md',
          glowAura: 'from-blue-500 to-cyan-500',
          themeBadgeText: shapeType === 'horizontal' ? 'HORIZ' : shapeType === 'vertical' ? 'VERT' : 'SQR',
        },
      };
  }
}
